### ISSUE TITLE
jmh tests

### ISSUE THREAD

**Issue by fommil** [scalaz/ioeffect#10]
we can easily add https://gitlab.com/fommil/sbt-neojmh or `sbt-jmh` but we need the perftests in the `src/jmh` directory to be able to run then.

@jdegoes any chance of making them available so we can check for regressions?

**Comment by jdegoes** [comment]
They are already in the `benchmarks` directory in the main Scalaz 8 repository.

**Comment by He-Pin** [comment]
It would be better to set up a CI with benchmarks.

**Comment by fommil** [comment]
@hepin1989 that'd be awesome, but we need consistent and dedicated hardware to be able to do it.

**Comment by fommil** [comment]
maybe in zio
