### ISSUE TITLE
unsafeRunAsync as part of RTS

### ISSUE THREAD

**Issue by jmcardon** [scalaz/ioeffect#25]
@jdegoes [can't back out now :grin:](https://gitter.im/scalaz/scalaz?at=5adcdecc62316e0505ea2221)

**Comment by jdegoes** [comment]
Oh no, evidence of my commitments!!! I'm doomed.

Will have a PR to main repo shortly.

**Comment by jdegoes** [comment]
Fixed [here](https://github.com/scalaz/scalaz/commit/d07918ba566b5e100e8af1597c12887e13958ea2).
