### ISSUE TITLE
Request: Scala Native support

### ISSUE THREAD

**Issue by danielyli** [scalaz/ioeffect#40]
I’m building an app using Scala Native, and pure FP IO is something I’d like to use. It would be great for `scalaz-ioeffect` to support Scala Native 0.3 like `scalaz-core`, `scalaz-effect`, `scalaz-iteratee`, etc. How difficult is this from a technical perspective?

**Comment by edmundnoble** [comment]
This would mean implementing an `RTS` from scratch. The difficulty will depend on your knowledge of Scala, unsafe backends for pure FP Scala, the Scala-JVM `RTS` we have in particular, the Java Memory Model, the scala-native memory model, and the scala-native compiler. If you know all this stuff well already, you just need to write out a thousand or so lines of code and come up with extensive tests, and add scala-native to the build matrix. So probably at least a week of work.

**Comment by fommil** [comment]
maybe in zio
