### ISSUE TITLE
IO.widen should apply to the A not the E

### ISSUE THREAD

**Issue by fommil** [scalaz/ioeffect#43]
This is inconsistent with `Functor.widen`

```scala
final def widen[E2](implicit ev: E <~< E2): IO[E2, A]
```

how about `.ewiden` ? Consistent with `.emap`

**Comment by ktonga** [comment]
Fixed in ~~Dotty~~ ZIO :blush:. It was renamed to `widenError`

**Comment by fommil** [comment]
did that other weird thing get renamed to `emap` too?

We should keep it open here though, unless zio is going to have a 7.2 backport.

**Comment by ktonga** [comment]
It will, I'm working on it scalaz/scalaz-zio#42
