### ISSUE TITLE
MonadIO instances

### ISSUE THREAD

**Issue by fommil** [scalaz/ioeffect#48]
I wonder if perhaps we should remove the `extends Monad` to be able to create instances for the scalaz mtl

**Comment by emilypi** [comment]
@edmundnoble were discussing this last night. Personally, I would prefer

`def liftIO[E, A](io: IO[E, A])(implicit M: Monad[M]): M[A]`

**Comment by fommil** [comment]
me too!

**Comment by emilypi** [comment]
@fommil he thinks we're dirty heathens 😦

**Comment by fommil** [comment]
We are dirty heathens, but we're also right about this :stuck_out_tongue:
