### ISSUE TITLE
SNAPSHOT instructions

### ISSUE THREAD

**Issue by fommil** [scalaz/ioeffect#51]
rather that publish binaries, we should note that this is how to declare a source dependency

```scala
val ioeffect = ProjectRef(
  uri("git://github.com/scalaz/ioeffect.git#1a3b397"),
  "ioeffect"
)
```

and then `.dependsOn(ioeffect)` instead of `libraryDependencies`

**Comment by ktonga** [comment]
Since which version of sbt/with which plugins is this possible?

**Comment by fommil** [comment]
I think it's always been there
