### ISSUE TITLE
MonadPlus instance seems wrong

### ISSUE THREAD

**Issue by fommil** [scalaz/ioeffect#59]
I think we can only provide MonadPlus when E is Unit. Otherwise we can't differentiate between failures and the empty failure, or maybe our Plus logic needs to be more advanced.

**Comment by ktonga** [comment]
Indeed it does! FYI https://github.com/scalaz/scalaz-zio/pull/58/commits/17af8bf7a786696c69e9a2c33ec45c2897ae2627
