### ISSUE TITLE
sonatype snapshot publish

### ISSUE THREAD

**Issue by fommil** [scalaz/ioeffect#7]
we need somebody with the sonatype creds to add these envvars

- `SONATYPE_USERWORD`
- `SONATYPE_PASSWORD`

or to populate `~/.m2/credentials`  as per https://gitlab.com/fommil/sbt-sensible/blob/master/src/main/scala/SonatypePlugin.scala

and to check that they are happy with the travis config.

Before doing that, I recommend renaming this repo to `scalaz-ioeffect`.

// @xuwei-k do you have rights?

**Comment by fommil** [comment]
OR we could setup a user just for this CI and raise a ticket with sonatype to give access to the `org.scalaz:scalaz-ioeffect_*` artefacts (or to create a sub-organisation).

**Comment by jdegoes** [comment]
It would be awesome to do this for Scalaz 8 too, as I've had many requests for snapshots for people who want to try it.

**Comment by fommil** [comment]
@xuwei-k do we have a `scalaz` user / password on `oss.sonatype.org` ? It would be very useful for CI.

**Comment by xuwei-k** [comment]
I have permissions for `org.scalaz`( maybe also @retronym ). What’s the meaning of `scalaz` user?(machine user?)
I think does not exists the `scalaz` user/password now.

- https://issues.sonatype.org/browse/OSSRH-2732
- https://github.com/scalaz/scalaz/pull/889

**Comment by fommil** [comment]
I'd rather people used source dependencies for snapshots.

Same goes for scalaz-core... no need for milestone releases either.
