### ISSUE TITLE
use the scalaz-core encoding of invariant case objects

### ISSUE THREAD

**Issue by fommil** [scalaz/ioeffect#8]
we don't need to use `Nothing` here, we have an encoding for this, see `INil` in the 7.3 branch.

```
private final case object Later extends AsyncReturn[Nothing]
```

https://github.com/scalaz/effect/blob/master/ioeffect/src/main/scala/scalaz/ioeffect/AsyncReturn.scala#L26

Also we can then do an exhaustive match instead of the `case _ => ` I see :scream:

**Comment by jbgi** [comment]
not that replacing `case _ => ` by `case INil() =>` increase the generated method size due to scalac adding a catch all `case _ => throw new MatchError()` at the end in this case. In return the method may no longer be inlined by JIT...

**Comment by jbgi** [comment]
but for non `@tailrec`, using higher level fold* methods is recommended to avoid that issue.

**Comment by fommil** [comment]
@jbgi yeah, everything is a trade-off based on the runtime perf and the readability of the code. I prefer perfworkarounds that localise the hack as much as possible, but if I was shown evidence that this slows down the `IO`, I'd of course yield to the performance... if we left a comment in the code referencing the results.

If we had an optimising compiler plugin, we could not only automatically apply this pattern, but also convert a trailing match on something like this into `case _ =>` and get the best of both worlds.

**Comment by jbgi** [comment]
> If we had an optimising compiler plugin, we could not only automatically apply this pattern, but also convert a trailing match on something like this into case _ => and get the best of both worlds.

Certainly worth a https://github.com/oleg-py/better-pattern-match ;-) /cc @oleg-py

Edit: benchmarks by @dwijnand for reference: https://github.com/dwijnand/l2jmh-try-fold-vs-patmat/blob/master/README.md

**Comment by fommil** [comment]
@jbgi that pattern match could also make use of iotaz / `IO.Tags` style coproduct hacks to switch on an integer for sealed traits.

*sigh* I feel like the FP community could have been implementing these things the past 3 years instead of ... well... what happened instead.
